name: kendamanomics_mobile
description: App used by kendama players to track their progress.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.1+18

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  provider: ^6.1.1
  kiwi: ^5.0.0
  easy_localization: ^3.0.4
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.3.4
  uuid: ^4.3.3
  shimmer: ^3.0.0
  video_player: ^2.8.2
  webview_flutter: ^4.7.0
  url_launcher: ^6.2.4
  tuple: ^2.0.2
  app_group_directory: ^2.0.0
  path_provider: ^2.1.2
  preload_page_view: ^0.2.0
  flutter_mailer: ^2.1.2
  in_app_purchase: ^3.1.13
  flutter_markdown: ^0.6.19
  gif: ^2.3.0
  permission_handler: ^11.3.0
  device_info_plus: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/localization/
    - assets/images/
    - assets/icon/
    - assets/config/
    - assets/gif/
    - assets/statics/
    - assets/release_configs/

  fonts:
    - family: GillSans
      fonts:
        - asset: assets/fonts/GillSans-Light.otf
          weight: 300
        - asset: assets/fonts/GillSans-Medium.otf
          weight: 500
#        - asset: assets/fonts/Quicksand-Bold.ttf
#          weight: 700